hot-fix:
it seems like AMP causes NANs due to overflow and crashes

/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:409: operator(): block: [983,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:409: operator(): block: [983,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.

Epoch   1 | Time:  36.36s | LR: 0.00001503:   1%|          | 2/300 [02:34<6:24:39, 77.45s/it]
Error executing job with overrides: ['dataset=same_task', 'dataset.dataset_name=same_task_y0ymax_unrelated20', 'dataset.sample_prior=False', 'experiment=slurm', 'experiment_name=same_y0ymax', 'device=cuda', 'model=ppfn_mha_hp', 'optimizer.lr=3e-4', '+trainer.trainer_class.eons=2', 'run_name=same_mha_hp', 'trainer.trainer_class.use_amp=True', 'device=cuda']
Traceback (most recent call last):

  File "/bigwork/nhwpruht/Meta_FTPFN/src/ppfn/model/mymodel/layers/adapter_wrapper.py", line 36, in forward
    A, B, C = self.adapter(A=A, B=B, C=C, sep=single_eval_pos, **adapter_kwargs)
  File "/bigwork/nhwpruht/Meta_FTPFN/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/bigwork/nhwpruht/Meta_FTPFN/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
    return forward_call(*args, **kwargs)
  File "/bigwork/nhwpruht/Meta_FTPFN/src/ppfn/model/mymodel/layers/mha_adapter_v2.py", line 177, in forward
    gate_mean=gate_values.mean().item()
torch.AcceleratorError: CUDA error: device-side assert triggered
Search for `cudaErrorAssert' in https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html for more information.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.